In [2]:
import pandas as pd
import uuid

In [1]:
patients = pd.read_csv(r'D:\DEPI\DEPI final project\data sources\patients.csv')
patients.info()

NameError: name 'pd' is not defined

In [4]:
patients.columns

Index(['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX',
       'FIRST', 'MIDDLE', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE',
       'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE',
       'COUNTY', 'FIPS', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES',
       'HEALTHCARE_COVERAGE', 'INCOME'],
      dtype='str')

In [19]:
patients.DRIVERS.head(10)

0          NaN
1    S99918355
2    S99914262
3          NaN
4    S99954548
5    S99966512
6    S99914459
7    S99912447
8    S99941379
9    S99997040
Name: DRIVERS, dtype: str

In [5]:
patients_df = pd.DataFrame(patients, columns=["Id", "FIRST", "MIDDLE", "LAST", "BIRTHDATE", "GENDER", "RACE", "CITY", "STATE", "HEALTHCARE_COVERAGE"])

In [6]:
patients_df.head()

,Id,FIRST,MIDDLE,LAST,BIRTHDATE,GENDER,RACE,CITY,STATE,HEALTHCARE_COVERAGE
0,d54bbddf-1ab7-d6b1-1964-f12313ec0729,Sol312,Tom274,Ondricka197,2025-07-09,M,black,Agawam,Massachusetts,0.00
1,2e6bf760-653f-e325-b20d-ebd85714d951,Jerri638,Lucinda68,Gislason620,2008-08-23,F,black,Boston,Massachusetts,0.00
2,0edbaaaf-ef5f-d58c-017e-004a706d388e,Son314,NaN,Dooley940,2006-04-28,M,white,New Bedford,Massachusetts,3035.29
3,4f1a6def-6365-ffd7-6c93-e10ce3b386b7,Danita413,NaN,Schumm995,2012-07-06,F,white,Brockton,Massachusetts,0.00
4,6531a1af-ef61-3596-3113-94649bff892c,Débora815,Carmen818,Jimínez732,2001-12-22,F,white,Holyoke,Massachusetts,365078.60

In [7]:
patients_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 114614 entries, 0 to 114613
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Id                   114614 non-null  str
 1   FIRST                114614 non-null  str
 2   MIDDLE               91728 non-null   str
 3   LAST                 114614 non-null  str
 4   BIRTHDATE            114614 non-null  str
 5   GENDER               114614 non-null  str
 6   RACE                 114614 non-null  str
 7   CITY                 114614 non-null  str
 8   STATE                114614 non-null  str
 9   HEALTHCARE_COVERAGE  114614 non-null  float64
dtypes: float64(1), str(9)
memory usage: 8.7 MB

In [8]:
patients_df.shape

(114614, 10)

In [9]:
patients_df.to_csv(r'D:\DEPI\DEPI final project\DATA_SOURCE_SQL\patients_df.csv',index=False)

In [10]:
patients_df.STATE.value_counts()

STATE
Massachusetts    114614
Name: count, dtype: int64

In [11]:
patients_df = patients_df.drop (columns="STATE")

In [12]:
patients_df.columns

Index(['Id', 'FIRST', 'MIDDLE', 'LAST', 'BIRTHDATE', 'GENDER', 'RACE', 'CITY',
       'HEALTHCARE_COVERAGE'],
      dtype='str')

In [24]:
patients_df.rename(
    columns={
        "Id": "patient_id",
        "MIDDLE": "middle_name",
        "FIRST": "first_name",
        "LAST": "last_name",
        "BIRTHDATE": "birth_date",
        "GENDER": "gender",
        "RACE": "race",
        "CITY": "city",
        "HEALTHCARE_COVERAGE": "insurance_type"
    },
    inplace=True
)

In [25]:
patients_df.columns = patients_df.columns.str.lower()

In [27]:
patients_df.head()

,patient_id,first_name,middle_name,last_name,birth_date,gender,race,city,insurance_type
0,d54bbddf-1ab7-d6b1-1964-f12313ec0729,Sol312,Tom274,Ondricka197,2025-07-09,M,black,Agawam,0.00
1,2e6bf760-653f-e325-b20d-ebd85714d951,Jerri638,Lucinda68,Gislason620,2008-08-23,F,black,Boston,0.00
2,0edbaaaf-ef5f-d58c-017e-004a706d388e,Son314,NaN,Dooley940,2006-04-28,M,white,New Bedford,3035.29
3,4f1a6def-6365-ffd7-6c93-e10ce3b386b7,Danita413,NaN,Schumm995,2012-07-06,F,white,Brockton,0.00
4,6531a1af-ef61-3596-3113-94649bff892c,Débora815,Carmen818,Jimínez732,2001-12-22,F,white,Holyoke,365078.60

In [28]:
patients_df.to_csv(r'D:\DEPI\DEPI final project\DATA_SOURCE_SQL\patients_df.csv',index=False)

In [29]:
medications = pd.read_csv(r'D:\DEPI\DEPI final project\data sources\medications.csv')
medications.info()

<class 'pandas.DataFrame'>
RangeIndex: 5668128 entries, 0 to 5668127
Data columns (total 13 columns):
 #   Column             Dtype
---  ------             -----
 0   START              str
 1   STOP               str
 2   PATIENT            str
 3   PAYER              str
 4   ENCOUNTER          str
 5   CODE               int64
 6   DESCRIPTION        str
 7   BASE_COST          float64
 8   PAYER_COVERAGE     float64
 9   DISPENSES          int64
 10  TOTALCOST          float64
 11  REASONCODE         float64
 12  REASONDESCRIPTION  str
dtypes: float64(4), int64(2), str(7)
memory usage: 562.2 MB

Index(['START', 'STOP', 'PATIENT', 'PAYER', 'ENCOUNTER', 'CODE', 'DESCRIPTION',
       'BASE_COST', 'PAYER_COVERAGE', 'DISPENSES', 'TOTALCOST', 'REASONCODE',
       'REASONDESCRIPTION'],
      dtype='str')

In [67]:
medications_df = pd.DataFrame(medications, columns=["PATIENT","ENCOUNTER","CODE","DESCRIPTION","START","STOP","TOTALCOST"])

In [ ]:
medications_df.head()

,PATIENT,ENCOUNTER,CODE,DESCRIPTION,START,STOP,TOTALCOST
0,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-dcfc-a59741d48b02,198405,Ibuprofen 100 MG Oral Tablet,2016-12-17T18:31:16Z,2017-01-03T18:31:16Z,22.29
1,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-434b-6a33c688f818,1535362,sodium fluoride 0.0272 MG/MG Oral Gel,2018-09-08T21:02:07Z,2018-09-08T21:02:07Z,129.94
2,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-01be-253ea44acc2c,834061,Penicillin V Potassium 250 MG Oral Tablet,2019-04-01T13:18:03Z,2019-04-10T14:18:03Z,20.65
3,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-e107-e2a2d88f74d7,1535362,sodium fluoride 0.0272 MG/MG Oral Gel,2019-09-14T20:29:15Z,2019-09-14T20:29:15Z,129.94
4,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-3669-44f38bf38ff5,978950,{5 (dienogest 2 MG / estradiol valerate 2 MG O...,2025-08-07T18:18:03Z,NaN,4586.40

In [68]:
medications_df.columns

Index(['PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'START', 'STOP',
       'TOTALCOST'],
      dtype='str')

In [70]:
uuids = [str(uuid.uuid4()) for _ in range(len(medications_df))]

medications_df.insert(0,"Medications_id",uuids)

medications_df.head()

,Medications_id,PATIENT,ENCOUNTER,CODE,DESCRIPTION,START,STOP,TOTALCOST
0,5e00a4ff-ae2b-4c53-a766-06dca9022240,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-dcfc-a59741d48b02,198405,Ibuprofen 100 MG Oral Tablet,2016-12-17T18:31:16Z,2017-01-03T18:31:16Z,22.29
1,7d87ad06-181a-4ca3-96fb-b22e3519fbb1,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-434b-6a33c688f818,1535362,sodium fluoride 0.0272 MG/MG Oral Gel,2018-09-08T21:02:07Z,2018-09-08T21:02:07Z,129.94
2,12734bda-3724-4079-a8e1-3dc0233023bc,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-01be-253ea44acc2c,834061,Penicillin V Potassium 250 MG Oral Tablet,2019-04-01T13:18:03Z,2019-04-10T14:18:03Z,20.65
3,384c00d1-13dd-4c09-b560-f664aac2c2b1,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-e107-e2a2d88f74d7,1535362,sodium fluoride 0.0272 MG/MG Oral Gel,2019-09-14T20:29:15Z,2019-09-14T20:29:15Z,129.94
4,b3af2363-3985-4d6f-bdaa-e2ae79727da4,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-3669-44f38bf38ff5,978950,{5 (dienogest 2 MG / estradiol valerate 2 MG O...,2025-08-07T18:18:03Z,NaN,4586.40

In [71]:
medications_df.columns

Index(['Medications_id', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION',
       'START', 'STOP', 'TOTALCOST'],
      dtype='str')

In [72]:
medications_df.rename(
    columns= {
        "Medications_id": "medication_id",
        "PATIENT": "patient_id",
        "ENCOUNTER": "encounter_id",
        "CODE": "drug_code",
        "DESCRIPTION": "description",
        "START": "start_date",
        "STOP": "stop_date",
        "TOTALCOST": "cost"
	},
	inplace=True
)

In [73]:
medications_df.to_csv(r'D:\DEPI\DEPI final project\DATA_SOURCE_SQL\medications_df.csv',index= False)

In [57]:
conditions = pd.read_csv(r'D:\DEPI\DEPI final project\data sources\conditions.csv')
conditions.columns

Index(['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'SYSTEM', 'CODE',
       'DESCRIPTION'],
      dtype='str')

In [ ]:
uuids = [str(uuid.uuid4()) for _ in range(len(conditions))]

conditions_df = pd.DataFrame(conditions, columns = ["PATIENT","ENCOUNTER","CODE","DESCRIPTION","START","STOP"])
conditions_df.head()

,PATIENT,ENCOUNTER,CODE,DESCRIPTION,START,STOP
0,d54bbddf-1ab7-d6b1-1964-f12313ec0729,d54bbddf-1ab7-d6b1-a49a-24e20ddc7100,314529007,Medication review due (situation),2025-07-09,2025-07-09
1,d54bbddf-1ab7-d6b1-1964-f12313ec0729,d54bbddf-1ab7-d6b1-09c5-f80dba9f2a9d,314529007,Medication review due (situation),2025-08-13,2025-10-15
2,d54bbddf-1ab7-d6b1-1964-f12313ec0729,d54bbddf-1ab7-d6b1-7a19-8ddc742f961b,314529007,Medication review due (situation),2025-12-17,NaN
3,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-176c-fd561c3c03dd,314529007,Medication review due (situation),2015-08-15,2016-08-20
4,2e6bf760-653f-e325-b20d-ebd85714d951,2e6bf760-653f-e325-1235-03978eff7331,444814009,Viral sinusitis (disorder),2016-05-19,2016-06-04

In [60]:
conditions_df.insert(0,"Condition_id",uuids)
conditions_df.columns

Index(['Condition_id', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'START',
       'STOP'],
      dtype='str')

In [61]:
conditions_df.rename(
    columns={
        "Condition_id": "condition_id",
        "PATIENT": "patient_id",
        "ENCOUNTER": "Encounter_id",
        "CODE": "icd10_code",
        "DESCRIPTION": "decription",
        "START": "onset_date",
        "STOP": "resolved_date"
	},
    inplace=True
)

In [62]:
conditions_df.to_csv(r'D:\DEPI\DEPI final project\DATA_SOURCE_SQL\conditions_df.csv',index= False)

In [42]:
encounters = pd.read_csv(r'D:\DEPI\DEPI final project\data sources\encounters.csv')

In [ ]:
encounters.columns

Index(['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PROVIDER', 'PAYER',
       'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST',
       'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE',
       'REASONDESCRIPTION'],
      dtype='str')

In [44]:
encounters_df = pd.DataFrame(encounters,columns = ["Id","PATIENT","PROVIDER","DESCRIPTION","START","STOP","TOTAL_CLAIM_COST"])
encounters_df.columns

Index(['Id', 'PATIENT', 'PROVIDER', 'DESCRIPTION', 'START', 'STOP',
       'TOTAL_CLAIM_COST'],
      dtype='str')

In [45]:
encounters_df.rename(
    columns={
        "Id": "encounter_id",
        "PATIENT": "patient_id",
        "PROVIDER": "provider_id",
        "DESCRIPTION": "encounter_type",
        "START": "start_time",
        "STOP": "end_time",
        "TOTAL_CLAIM_COST": "totel_cost"
    },
    inplace=True
)

In [46]:
encounters_df.to_csv(r'D:\DEPI\DEPI final project\DATA_SOURCE_SQL\Encounters_df.csv',index=False)

In [30]:
providers = pd.read_csv(r'D:\DEPI\DEPI final project\data sources\providers.csv')
providers.columns

Index(['Id', 'ORGANIZATION', 'NAME', 'GENDER', 'SPECIALITY', 'ADDRESS', 'CITY',
       'STATE', 'ZIP', 'LAT', 'LON', 'ENCOUNTERS', 'PROCEDURES'],
      dtype='str')

In [32]:
providers_df = pd.DataFrame(providers , columns= ["Id","NAME","SPECIALITY","ORGANIZATION","CITY"])
providers_df.columns

Index(['Id', 'NAME', 'SPECIALITY', 'ORGANIZATION', 'CITY'], dtype='str')

In [33]:
providers_df.rename(
    
	columns = {
		"Id": "provider_id",
        "NAME": "name",
        "SPECIALITY": "specialty",
        "ORGANIZATION": "organization_id",
        "CITY": "city"
	},
    inplace=True
)

In [34]:
providers_df.columns = providers_df.columns.str.lower()

In [35]:
providers_df.columns

Index(['provider_id', 'name', 'specialty', 'organization_id', 'city'], dtype='str')

In [36]:
providers_df.to_csv(r'D:\DEPI\DEPI final project\DATA_SOURCE_SQL\providers_df.csv',index=False)

In [37]:
organizations = pd.read_csv(r'D:\DEPI\DEPI final project\data sources\organizations.csv')
organizations.columns

Index(['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'PHONE',
       'REVENUE', 'UTILIZATION'],
      dtype='str')

In [39]:
organizations_df = pd.DataFrame(organizations,columns= ["Id","NAME","CITY","STATE"])
organizations_df.columns

Index(['Id', 'NAME', 'CITY', 'STATE'], dtype='str')

In [40]:
organizations_df.rename(
    columns={
        "Id": "id",
        "NAME": "name",
        "CITY": "city",
        "STATE": "state",
	},
	inplace=True
)

In [41]:
organizations_df.to_csv(r'D:\DEPI\DEPI final project\DATA_SOURCE_SQL\organization_df.csv',index=False)

In [8]:
claims = pd.read_json(r'D:\DEPI\DEPI final project\data sources\claims_Table.json',lines=True)

In [9]:
claims.columns

Index(['claim_id', 'patient_id', 'encounter_id', 'amount_billed',
       'amount_paid', 'status', 'denial_reason', 'payer_id'],
      dtype='str')

In [10]:
claims_df = pd.DataFrame(claims,columns=["claim_id","patient_id","encounter_id","payer_id","amount_billed","amount_paid","status"])

In [11]:
claims_df.rename(
    columns={
        "claim_id": "claim_id",
        "patient_id": "patient_id",
        "encounter_id": "encounter_id",
        "payer_id": "payer_id",
        "amount_billed": "amount_billed",
        "amount_paid": "amount_paid",
        "status": "Status"
    },
    inplace=True
)

In [12]:
claims_df.columns

Index(['claim_id', 'patient_id', 'encounter_id', 'payer_id', 'amount_billed',
       'amount_paid', 'Status'],
      dtype='str')

In [13]:
# claims_df.shape
claims_df = claims_df.drop_duplicates("claim_id")

In [14]:
claims_df.shape

(182622, 7)

In [15]:
claims_df.to_csv(r'D:\DEPI\DEPI final project\DATA_SOURCE_SQL\claims_df.csv',index=False)

In [16]:
payers = pd.read_json(r'D:\DEPI\DEPI final project\data sources\payer.json',lines=True)
payers.columns

Index(['payer_id', 'payer_name'], dtype='str')

In [21]:
payers.head(10)

   payer_id             payer_name
0         1            Brian Jones
1         2            Amy Collins
2         3         Christina Bell
3         4            Hunter Yang
4         5            Alan Miller
5         6       Christina Greene
6         7          Eric Phillips
7         8         Steven Kennedy
8         9  Mr. Richard Rodriguez
9        10            Kevin Evans

In [22]:
payers.to_csv(r'D:\DEPI\DEPI final project\DATA_SOURCE_SQL\payers.csv',index=False)